version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-inicial
    ports:
      - "5000:5000"
    environment:
      - TITULO=K8S Conceitos 05-01-2024
      - MENSAGEM=Atenção ao nome do Host!
