apiVersion: batch/v1
kind: CronJob
metadata:
  name: teste-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: teste-cronjob
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  echo "Executando job em: $(date)"
                  echo "================================================================================"
                  echo " /\\_/\\"
                  echo "( o.o )"
                  echo " > ^ <"
                  echo "================================================================================"
          restartPolicy: OnFailure
