apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste-app-deployment-emerson
spec:
  replicas: 3 # Defina o número de réplicas desejado
  selector:
    matchLabels:
      run: teste-app
  template:
    metadata:
      labels:
        run: teste-app
    spec:
      containers:
        - image: fmnapoli/teste-app:2.0.0
          name: teste-app
          env:
            - name: TITULO
              value: "K8S Deployment Emerson"
            - name: MENSAGEM
              value: "Testando Deployment 1 Emerson"
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
