# apiVersion: networking.k8s.io/v1beta1 # for k3s < v1.19
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teste-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: k8steam.tdevopslab.tk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teste-app-service
                port:
                  number: 5000
