apiVersion: batch/v1
kind: Job
metadata:
  name: teste-job
spec:
  template:
    spec:
      containers:
        - name: teste-job
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              echo "Executando job em: $(date)"
              echo "================================================================================"
              echo " /\\_/\\"
              echo "( o.o )"
              echo " > ^ <"
              echo "================================================================================"
      restartPolicy: OnFailure
