apiVersion: v1
kind: Pod
metadata:
  labels:
    run: teste-app
  name: teste-app
spec:
  containers:
    - image: fmnapoli/teste-app:1.0.0
      name: teste-app
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
