apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: teste-app-rs
spec:
  replicas: 5 # Defina o número de réplicas desejado
  selector:
    matchLabels:
      run: teste-app
  template:
    metadata:
      labels:
        run: teste-app
    spec:
      containers:
        - image: fmnapoli/teste-app:1.0.0
          name: teste-app
          env:
            - name: TITULO
              value: "K8S Replicaset"
            - name: MENSAGEM
              value: "Testando Replicaset 1"
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
