apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      securityContext:
        fsGroupChangePolicy: Always
        sysctls: []
        supplementalGroups: []
        fsGroup: 0
      containers:
        - name: odoo
          image: odoo:17
          ports:
            - containerPort: 8069
          envFrom:
            - configMapRef:
                name: odoo-config
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - name: odoo-web-data
              mountPath: /var/lib/odoo
          resources: {}
      volumes:
        - name: odoo-web-data
          persistentVolumeClaim:
            claimName: odoo-web-data-pvc
