    [general]
    host = "0.0.0.0"
    port = 5432
    admin_username = "odoo"
    admin_password = "cf05-7de2-4ba4-98c"

    # [pools.treinamento]
    # pool_mode = "transaction"
    # default_role = "any"
    # query_parser_enabled = true
    # query_parser_read_write_splitting = true

    [pools.postgres.users.0]
    username = "postgres"
    password = "cf05-7de2-4ba4-98c"
    pool_size = 10
    min_pool_size = 1
    pool_mode = "transaction"

    [pools.postgres.shards.0]

    servers = [
      ["odoo-postgres", 5432, "primary"]
    ]

    # servers = [
    #   ["odoo-postgres-primary", 5432, "primary"],
    #   ["odoo-postgres-replicas", 5432, "replica"]
    #  ]

    database = "postgres"    

    [pools.treinamento.users.0]
    username = "odoo"
    password = "cf05-7de2-4ba4-98c"
    pool_size = 10
    min_pool_size = 1
    pool_mode = "transaction"

    [pools.treinamento.shards.0]

    servers = [
      ["odoo-postgres", 5432, "primary"]
    ]

    # servers = [
    #   ["odoo-postgres-primary", 5432, "primary"],
    #   ["odoo-postgres-replicas", 5432, "replica"]
    #  ]

    database = "treinamento"